<?php

############################################################
#       LOGO/LANGS.PHP                                     #
#       names and contents of languages                    #
#       first shown on pages with selection                #
############################################################
#       if you translate to new language,                  #
#       please use UTF-8 charset entities                  #
#       (for compatibility)                                #
############################################################

$lang = [
    'eng' => [
        'logo.images.no_gd_library' => 'GD2 library is not present!',
        'logo.images.no_imagemagick' => 'ImageMagic not installed or too old!',
        'logo.images.cannot_create_from_resource' => 'Cannot create image from resource!',
        'logo.images.cannot_save_resource' => 'Cannot save image resource!',
        'logo.images.unknown_type' => 'Unknown format *%s*',
        'logo.images.bad_instance' => 'Wrong instance of *%s*, must be instance of \kalanis\kw_images\Graphics\Format\AFormat',
        'logo.images.wrong_file_mime' => 'Wrong file mime type - got *%s*',
        'logo.images.compare_size_not_set' => 'Sizes to compare are not set.',
        'logo.images.image_cannot_be_resized' => 'Image cannot be resized!',
        'logo.images.image_cannot_be_resampled' => 'Image cannot be resampled!',
        'logo.images.image_cannot_create_empty' => 'Cannot create empty image!',
        'logo.images.image_cannot_get_size' => 'Cannot get image size!',
        'logo.images.image_load_first' => 'You must load image first.',
        'logo.images.description_cannot_remove' => 'Cannot remove description!',
        'logo.images.description_cannot_find' => 'Cannot find that description.',
        'logo.images.description_already_exists' => 'Description with the same name already exists here.',
        'logo.images.description_cannot_remove_old' => 'Cannot remove old description.',
        'logo.images.description_cannot_copy' => 'Cannot copy base description.',
        'logo.images.description_cannot_move' => 'Cannot move base description.',
        'logo.images.description_cannot_rename' => 'Cannot rename base description.',
        'logo.images.thumb_dir_cannot_remove' => 'Cannot remove dir thumb!',
        'logo.images.thumb_cannot_remove_current' => 'Cannot remove current thumb!',
        'logo.images.image_cannot_read_size' => 'Cannot read file size. It exists?',
        'logo.images.image_too_large' => 'This image is too large to use.',
        'logo.images.image_cannot_find' => 'Cannot find that image.',
        'logo.images.image_cannot_remove' => 'Cannot remove image.',
        'logo.images.image_already_exists' => 'Image with the same name already exists here.',
        'logo.images.image_cannot_remove_old' => 'Cannot remove old image.',
        'logo.images.image_cannot_copy' => 'Cannot copy base image.',
        'logo.images.image_cannot_move' => 'Cannot move base image.',
        'logo.images.image_cannot_rename' => 'Cannot rename base image.',
        'logo.images.thumb_cannot_find' => 'Cannot find that thumb.',
        'logo.images.thumb_cannot_remove' => 'Cannot remove thumb!',
        'logo.images.thumb_already_exists' => 'Thumb with the same name already exists here.',
        'logo.images.thumb_cannot_remove_old' => 'Cannot remove old thumb.',
        'logo.images.image_cannot_get_base' => 'Cannot get base image.',
        'logo.images.image_cannot_store_temp' => 'Cannot store temporary image.',
        'logo.images.image_cannot_load_temp' => 'Cannot load temporary image.',
        'logo.images.thumb_cannot_copy' => 'Cannot copy base thumb.',
        'logo.images.thumb_cannot_move' => 'Cannot move base thumb.',
        'logo.images.thumb_cannot_rename' => 'Cannot rename base thumb.',

        'logo.page' => 'Logo',
    ],
    'cze' => [
        'logo.images.no_gd_library' => 'Knihovna GD2 není k dispozici!',
        'logo.images.no_imagemagick' => 'ImageMagic není k dispozici nebo je zastaralý!',
        'logo.images.cannot_create_from_resource' => 'Z těchto zdrojových dat nejde načíst obrázek!',
        'logo.images.cannot_save_resource' => 'Připravený obrázek nejde uložit do zdrojových dat!',
        'logo.images.unknown_type' => 'Neznámý formát *%s*',
        'logo.images.bad_instance' => 'Špatný objekt *%s*, musí to být instance třídy \kalanis\kw_images\Graphics\Format\AFormat',
        'logo.images.wrong_file_mime' => 'Špatný typ souboru - přišel *%s*',
        'logo.images.compare_size_not_set' => 'Nejsou nastavené velikosti k porovnání.',
        'logo.images.image_cannot_be_resized' => 'Obrázek nejde oříznout!',
        'logo.images.image_cannot_be_resampled' => 'Nejde změnit velikost obrázku!',
        'logo.images.image_cannot_create_empty' => 'Nemohu vytvořit prázdný obrázek!',
        'logo.images.image_cannot_get_size' => 'Nelze načíst velikost obrázku!',
        'logo.images.image_load_first' => 'Nejdříve je třeba načíst obrázek.',
        'logo.images.description_cannot_remove' => 'Nelze odstranit popisek!',
        'logo.images.description_cannot_find' => ' Popisek nelze načíst.',
        'logo.images.description_already_exists' => 'Popisek s tímto jménem už tu je.',
        'logo.images.description_cannot_remove_old' => 'Nemohu odstranit starý popisek.',
        'logo.images.description_cannot_copy' => 'Nemohu zkopírovat popisek.',
        'logo.images.description_cannot_move' => 'Nemohu přesunout popisek.',
        'logo.images.description_cannot_rename' => 'Nehohu přejmenovat popisek.',
        'logo.images.thumb_dir_cannot_remove' => 'Nemohu odstranit náhled složky!',
        'logo.images.thumb_cannot_remove_current' => 'Nemohu odstranit aktuální náhled!',
        'logo.images.image_cannot_read_size' => 'Nemohu načíst velikost obrázku. Existsuje vůbec?',
        'logo.images.image_too_large' => 'Tento obrázek je pro místní užití až moc velký.',
        'logo.images.image_cannot_find' => 'Nemohu najít obrázek.',
        'logo.images.image_cannot_remove' => 'Nemohu odstranit obrázek.',
        'logo.images.image_already_exists' => 'Obrázek s tímto jménem už tu je.',
        'logo.images.image_cannot_remove_old' => 'Nemohu odstranit starý obrázek.',
        'logo.images.image_cannot_copy' => 'Nemohu zkopírovat obrázek.',
        'logo.images.image_cannot_move' => 'Nemohu přesunout obrázek.',
        'logo.images.image_cannot_rename' => 'Nemohu přejmenovat obrázek.',
        'logo.images.thumb_cannot_find' => 'Nemohu najít náhled.',
        'logo.images.thumb_cannot_remove' => 'Nemohu odstranit náhled.',
        'logo.images.thumb_already_exists' => 'Náhled s tímto jménem už tu je.',
        'logo.images.thumb_cannot_remove_old' => 'Nemohu odstranit starý náhled.',
        'logo.images.image_cannot_get_base' => 'Nemohu načíst obrázek z úložiště.',
        'logo.images.image_cannot_store_temp' => 'Nemohu uložit dočasný obrázek.',
        'logo.images.image_cannot_load_temp' => 'Nemohu načíst dočasný obrázek.',
        'logo.images.thumb_cannot_copy' => 'Nemohu zkopírovat náhled.',
        'logo.images.thumb_cannot_move' => 'Nemohu přesunout náhled.',
        'logo.images.thumb_cannot_rename' => 'Nemohu přejmenovat náhled.',

        'logo.page' => 'Logo',
    ],
];
