<?php

############################################################
#       SHORT/LANGS.PHP                                    #
#       names and contents of languages                    #
#       first shown on pages with selection                #
############################################################
#       if you translate to new language,                  #
#       please use UTF-8 charset entities                  #
#       (for compatibility)                                #
############################################################

$lang = [
    'eng' => [
        "{UPLOAD}"=>"Upload",
        "{CHDIR}"=>"Change dir",
        "{NAME}"=>"Name",
        "{DESC}"=>"Description",
        "{MOVE_TO}"=>"Move to",
        "{COPY_TO}"=>"Copy to",
        "{DELETE}"=>"Delete",
        "{DIR_PROPS}"=>"About dir",
        "{DIR_NEW}"=>"New sub-dir",

        "{UPLOAD_TEXT}"=>"Upload image",
        "{DESCRIPTION}"=>"Description",
        "{UPLOAD_NOTE}"=>"Details - max 1024 x 1024 px, 2MB",


        "{FILE_NOT_EXISTS}"=>"File doesn't exists.",
        "{DIR_NOT_EXISTS}"=>"Dir doesn't exists.",
        "{TARGET_DIR_NOT_EXISTS}"=>"Target dir doesn't exists.",
        "{FILE_ALREADY_EXISTS}"=>"File already exists.",
        "{CANNOT_CREATE_THUMB_DIR}"=>"Couldn't create thumb dir.",
        "{CANNOT_CREATE_DESC_DIR}"=>"Couldn't create desc dir.",
        "{MAIN_IMAGE_NOT_COPY}"=>"Couldn't copy main image.",
        "{THUMB_IMAGE_NOT_COPY}"=>"Couldn't copy thumbnail image.",
        "{DESC_FILE_NOT_COPY}"=>"Couldn't copy description.",
        "{MAIN_IMAGE_NOT_MOVED}"=>"Couldn't move main image.",
        "{THUMB_IMAGE_NOT_MOVED}"=>"Couldn't move thumb image.",
        "{DESC_FILE_NOT_MOVED}"=>"Couldn't move description.",
        "{MAIN_IMAGE_NOT_RENAMED}"=>"Couldn't rename main image.",
        "{THUMB_IMAGE_NOT_RENAMED}"=>"Couldn't rename thumb image.",
        "{DESC_FILE_NOT_RENAMED}"=>"Couldn't rename description.",
        "{MAIN_IMAGE_NOT_DELETED}"=>"Couldn't remove main image.",
        "{THUMB_IMAGE_NOT_DELETED}"=>"Couldn't remove thumb image.",
        "{DESC_FILE_NOT_DELETED}"=>"Couldn't remove description.",
        "{CANNOT_WRITE}"=>"Cannot write.",
        "{UNKNOWN_SUFFIX}"=>"Unknown suffix/extension.",
        "{BAD_MIME_CONTENT_TYPE}"=>"unknown type/mime",
        "{WIDTH_MORE_THAN}"=>"Image is widther than ",
        "{HEIGHT_MORE_THAN}"=>"Image is higher than ",
        "{NOT_IMAGE_DETAILS}"=>"Couldn't get image details.",
        "{IMAGEMAGICK_NOT_AVAILABLE}"=>"Imagemagick not found.",
        "{GD2_LIBARY_NOT_AVAILABLE}"=>"GD2 not found.",
        "{ERROR_WITH_SUFFIX}"=>"Error with suffix.",
        "{CANNOT_SAVE_THUMB}"=>"Cannot save thumbnail.",
        "{CANNOT_WRITE_DESC}"=>"Cannot write description.",
        "{FILE_NOT_MOVED_FROM_TEMP}"=>"Cannot move image from temp.",
        "{FILE_NOT_UPLOADED}"=>"Image not uploaded.",
        "{DIR_ALREADY_EXISTS}"=>"Directory already exists.",
        "{DIR_CONTAIN_UNACCEPT_CHARS}"=>"Name contains unallowed characters.",
        "{NOT_CREATED}"=>"Cannot create dir.",
        "{CANNOT_WRITE}"=>"Cannot write.",

        "{LOADED}"=>"Loaded:",
        "{NOSCRIPT}"=>"Siabling scripts did problems with page. Your problem",
        "{CLICK_CLOSE}"=>"Click to close.",

        "{IMAGE_UPLOAD}"=>"Upload",
        "{IMAGE_COPY}"=>"Copy",
        "{IMAGE_MOVE}"=>"Move",
        "{IMAGE_RENAME}"=>"Rename",
        "{IMAGE_DELETE}"=>"Delete",
        "{IMAGE_PROPS}"=>"Properties",
        "{IMAGE_DIR_PROPS}"=>"Dir properties",
        "{IMAGE_DIR_NEW}"=>"New dir",

        /*        "{EDIT_FILE_TEXT}"=>"Upravuj",
                "{SAVE_TEXT}"=>"Ulo&#x017E;en&#x00ED;",
                "{CONTINUE}"=>"Pokra&#x010D;ovat",
                "{FILENAME_SET}"=>"Vyber soubor",
                "{DIRECTORY_TREE_SET}"=>"Vyber slo&#x017E;ku",*/

        "{FILES-DIRS}"=>"Files and dirs",
        "{OF}"=>"of",
        "{FILE_OPEN_ANOTHER_USER}"=>"File open another one.",

        "{MODULE_PAGE}"=>"Images",

        "short.add_record"=>"Add message",
        "short.update_texts"=>"Update texts",
        "short.remove_record"=>"Remove message",

        "short.id"=>"ID",
        "short.title"=>"Title",
        "short.message"=>"Message",
        "short.date"=>"Date",
        "short.actions"=>"Actions",
        "short.updated"=>"Updated",
        "short.removed"=>"Removed",

        "short.create_new_file"=>"New file was created.",
        "short.cannot_read"=>"No file with messages found.",
        "short.cannot_write"=>"Couldn't write data.",

        "short.add_message"=>"Add message",
        "short.update_message"=>"Actualize messages",
        "short.remove_message"=>"Remove messages",

        "short.page"=>"Short messages",
    ],
    'fra' => [
        "{UPLOAD}"=>"T&#x00E9;l&#x00E9;charger",
        "{CHDIR}"=>"Changenment le composant",
        "{NAME}"=>"Nom",
        "{DESC}"=>"Description",
        "{MOVE_TO}"=>"D&#x00E9;placer &#x00E0;",
        "{COPY_TO}"=>"Copie &#x00E0;",
        "{DELETE}"=>"Supprimer",
        "{DIR_PROPS}"=>"A propos de composant",
        "{DIR_NEW}"=>"Le composant noveau",

        "{UPLOAD_TEXT}"=>"T&#x00E9;l&#x00E9;charger la photo",
        "{DESCRIPTION}"=>"Description",
        "{UPLOAD_NOTE}"=>"D&#x00E9;tails - max 1024 x 1024 px, 2MB",


        "{FILE_NOT_EXISTS}"=>"Le fichier n'existe pas.",
        "{DIR_NOT_EXISTS}"=>"Le composant n'existe pas.",
        "{TARGET_DIR_NOT_EXISTS}"=>"Le composant cible existe d&#x00E9;j&#x00E0;.",
        "{FILE_ALREADY_EXISTS}"=>"Le fichier cible existe d&#x00E9;j&#x00E0;.",
        "{CANNOT_CREATE_THUMB_DIR}"=>"Ne pouvez pas cr&#x00E9;er composant du extrait.",
        "{CANNOT_CREATE_DESC_DIR}"=>"Ne pouvez pas cr&#x00E9;er composant du description.",
        "{MAIN_IMAGE_NOT_COPY}"=>"Ne pouvez pas copier l'image principale.",
        "{THUMB_IMAGE_NOT_COPY}"=>"Ne pouvez pas copier l'image extrait.",
        "{DESC_FILE_NOT_COPY}"=>"Ne pouvez pas copier la description.",
        "{MAIN_IMAGE_NOT_MOVED}"=>"Ne pouvez pas d&#x00E9;placer l'image principale.",
        "{THUMB_IMAGE_NOT_MOVED}"=>"Ne pouvez pas d&#x00E9;placer l'image extrait.",
        "{DESC_FILE_NOT_MOVED}"=>"Ne pouvez pas d&#x00E9;placer la description.",
        "{MAIN_IMAGE_NOT_RENAMED}"=>"Ne pouvez pas renommer l'image principale.",
        "{THUMB_IMAGE_NOT_RENAMED}"=>"Ne pouvez pas renommer l'image extrait.",
        "{DESC_FILE_NOT_RENAMED}"=>"Ne pouvez pas renommer la description.",
        "{MAIN_IMAGE_NOT_DELETED}"=>"Ne pouvez pas supprimer l'image principale.",
        "{THUMB_IMAGE_NOT_DELETED}"=>"Ne pouvez pas supprimer l'image extrait.",
        "{DESC_FILE_NOT_DELETED}"=>"Ne pouvez pas supprimer la description.",
        "{CANNOT_WRITE}"=>"Ne peut pas &#x00E9;crire.",
        "{UNKNOWN_SUFFIX}"=>"Suffixe inconnu.",
        "{BAD_MIME_CONTENT_TYPE}"=>"Le contenu est inconnu.",
        "{WIDTH_MORE_THAN}"=>"L'image est plus large que ",
        "{HEIGHT_MORE_THAN}"=>"L'image est plus large que ",
        "{NOT_IMAGE_DETAILS}"=>"D&#x00E9;tails de l'image inconnu.",
        "{IMAGEMAGICK_NOT_AVAILABLE}"=>"Imagemagick pas disponsible,",
        "{GD2_LIBARY_NOT_AVAILABLE}"=>"GD2 pas disponsible.;",
        "{ERROR_WITH_SUFFIX}"=>"Erreur Suffixe.",
        "{CANNOT_SAVE_THUMB}"=>"Ne peut pas cd&#x00E9;er l'extrait.",
        "{CANNOT_WRITE_DESC}"=>"Ne peut pas cr&#x00E9;er la description.",
        "{FILE_NOT_MOVED_FROM_TEMP}"=>"Impossible de d&#x00E9;placer l'image &#x00E0;partir de temporaries.",
        "{FILE_NOT_UPLOADED}"=>"L'image n'a pas transf&#x00E9;r&#x00E9;",
        "{DIR_ALREADY_EXISTS}"=>"Le composant existe d&#x00E9;j&#x00E0;.",
        "{DIR_CONTAIN_UNACCEPT_CHARS}"=>"Le nom contient signes nonautoris&#x00E9;s.",
        "{NOT_CREATED}"=>"Pas cr&#x00E9;&#x00E9;.",

        "{LOADED}"=>"Transf&#x00E9;r&#x00E9;:",
        "{NOSCRIPT}"=>"Interdiction le script pour charger ne permet pas la page correctement. Votre probl&#x00E8;me.",
        "{CLICK_CLOSE}"=>"Cliquez pour fermer",

        "{IMAGE_UPLOAD}"=>"T&#x00E9;l&#x00E9;charger",
        "{IMAGE_COPY}"=>"Copier",
        "{IMAGE_MOVE}"=>"D&#x00E9;placer",
        "{IMAGE_RENAME}"=>"Renommer",
        "{IMAGE_DELETE}"=>"Supprimer",
        "{IMAGE_PROPS}"=>"Propri&#x00E9;t&#x00E9;s",
        "{IMAGE_DIR_PROPS}"=>"Propri&#x00E9;t&#x00E9;s du composant",
        "{IMAGE_DIR_NEW}"=>"Le composant noveau",

        /*        "{EDIT_FILE_TEXT}"=>"Upravuj",
                "{SAVE_TEXT}"=>"Ulo&#x017E;en&#x00ED;",
                "{CONTINUE}"=>"Pokra&#x010D;ovat",
                "{FILENAME_SET}"=>"Vyber soubor",
                "{DIRECTORY_TREE_SET}"=>"Vyber slo&#x017E;ku",*/

        "{FILES-DIRS}"=>"Composants et fichiers",
        "{OF}"=>"de",
        "{FILE_OPEN_ANOTHER_USER}"=>"Le fichier est ouvr&#x00E9; par d'autre utilisateur.",

        "{MODULE_PAGE}"=>"Photos",

        "short.add_record"=>"Ajouter un message",
        "short.update_texts"=>"Actualiser un message",
        "short.remove_record"=>"Retrier le message.",

        "short.id"=>"ID",
        "short.title"=>"Titre",
        "short.message"=>"Message",
        "short.date"=>"Date",
        "short.actions"=>"Actions",
        "short.updated"=>"Actualis&#x00E9;",
        "short.removed"=>"Retri&#x00E9;",

        "short.create_new_file"=>"Cr&#x00E9;e le nouveau fichier",
        "short.cannot_read"=>"No file with messages found.",
        "short.cannot_write"=>"Ne peut pas &#x00E9;crire des donn&#x00E9;es.",

        "short.add_message"=>"Ajouter un message",
        "short.update_message"=>"Actualizer des messages",
        "short.remove_message"=>"Retrier des messages",

        "short.page"=>"Messages court",
    ],
    'cze' => [
        "{UPLOAD}"=>"Nahr&#x00E1;t",
        "{CHDIR}"=>"Zm&#x011B;&#x0148; slo&#x017E;ku",
        "{NAME}"=>"Jm&#x00E9;no",
        "{DESC}"=>"Popisek",
        "{MOVE_TO}"=>"P&#x0159;esun do",
        "{COPY_TO}"=>"Kopie do",
        "{DELETE}"=>"Sma&#x017E;",
        "{DIR_PROPS}"=>"O slo&#x017E;ce",
        "{DIR_NEW}"=>"Nov&#x00E1; slo&#x017E;ka",

        "{UPLOAD_TEXT}"=>"Nahraj obr&#x00E1;zek",
        "{DESCRIPTION}"=>"Popisek",
        "{UPLOAD_NOTE}"=>"Detaily - max 1024 x 1024 px, 2MB",
        "{UPDATE}"=>"Vlastnosti",
        "{UPDATE_THUMB}"=>"Aktualizovat n&#x00E1;hled",


        "{FILE_NOT_EXISTS}"=>"Soubor neexistuje",
        "{DIR_NOT_EXISTS}"=>"Slo&#x017E;ka neexistuje",
        "{TARGET_DIR_NOT_EXISTS}"=>"C&#x00ED;lov&#x00E1; slo&#x017E;ka neexistuje",
        "{FILE_ALREADY_EXISTS}"=>"Soubor u&#x017E; existuje",
        "{CANNOT_CREATE_THUMB_DIR}"=>"Nelze vytvo&#x0159;it slo&#x017E;ku n&#x00E1;hled&#x016F;",
        "{CANNOT_CREATE_DESC_DIR}"=>"Slo&#x017E;ka neexistuje",
        "{MAIN_IMAGE_NOT_COPY}"=>"Hlavn&#x00ED; obr&#x00E1;zek ne&#x0161;lo zkop&#x00ED;rovat",
        "{THUMB_IMAGE_NOT_COPY}"=>"N&#x00E1;hled ne&#x0161;lo zkop&#x00ED;rovat",
        "{DESC_FILE_NOT_COPY}"=>"Popisek ne&#x0161;lo zkop&#x00ED;rovat",
        "{MAIN_IMAGE_NOT_MOVED}"=>"Hlavn&#x00ED; obr&#x00E1;zek ne&#x0161;lo p&#x0159;esunout",
        "{THUMB_IMAGE_NOT_MOVED}"=>"N&#x00E1;hled ne&#x0161;lo p&#x0159;esunout",
        "{DESC_FILE_NOT_MOVED}"=>"Popisek ne&#x0161;lo p&#x0159;esunout",
        "{MAIN_IMAGE_NOT_RENAMED}"=>"Hlavn&#x00ED; obr&#x00E1;zek ne&#x0161;lo p&#x0159;ejemnovat",
        "{THUMB_IMAGE_NOT_RENAMED}"=>"N&#x00E1;hled ne&#x0161;lo p&#x0159;ejmenovat",
        "{DESC_FILE_NOT_RENAMED}"=>"Popisek ne&#x0161;lo p&#x0159;ejmenovat",
        "{MAIN_IMAGE_NOT_DELETED}"=>"Hlavn&#x00ED; obr&#x00E1;zek ne&#x0161;lo smazat",
        "{THUMB_IMAGE_NOT_DELETED}"=>"N&#x00E1;hled ne&#x0161;lo smazat",
        "{DESC_FILE_NOT_DELETED}"=>"Popisek ne&#x0161;lo smazat",
        "{CANNOT_WRITE}"=>"Ne&#x0161;lo zapsat",
        "{UNKNOWN_SUFFIX}"=>"Nezn&#x00E1;m&#x00E1; p&#x0159;&#x00ED;pona",
        "{BAD_MIME_CONTENT_TYPE}"=>"Nezn&#x00E1;m&#x00FE; obsah",
        "{WIDTH_MORE_THAN}"=>"Obr&#x00E1;zek je &#x0161;ir&#x0161;&#x00ED; ne&#x017E; ",
        "{HEIGHT_MORE_THAN}"=>"Obr&#x00E1;zek je vy&#x0161;&#x0161;&#x00ED; ne&#x017E; ",
        "{NOT_IMAGE_DETAILS}"=>"Nem&#x00E1;m detaily obr&#x00ED;zku.",
        "{IMAGEMAGICK_NOT_AVAILABLE}"=>"Imagemagick nen&#x00ED; k m&#x00E1;n&#x00ED;",
        "{GD2_LIBARY_NOT_AVAILABLE}"=>"GD2 nen&#x00ED; k m&#x00E1;n&#x00ED;",
        "{ERROR_WITH_SUFFIX}"=>"Chyba p&#x0159;&#x00ED;pony.",
        "{CANNOT_SAVE_THUMB}"=>"Nelze ulo&#x017E; n&#x00E1;hled",
        "{CANNOT_WRITE_DESC}"=>"Nelze ulo&#x017E; popisek",
        "{FILE_NOT_MOVED_FROM_TEMP}"=>"Obr&#x00E1;zek nelze dostat z do&#x010D;sn&#x00E9;ho um&#x00ED;st&#x011B;n&#x00ED;",
        "{FILE_NOT_UPLOADED}"=>"Obr&#x00E1;zek nebyl nahr&#x00E1;n",
        "{DIR_ALREADY_EXISTS}"=>"Slo&#x017E;ka ji&#x017E; existuje",
        "{DIR_CONTAIN_UNACCEPT_CHARS}"=>"N&#x00E1;zev obsahuje nepovolen&#x00E9; znaky",
        "{NOT_CREATED}"=>"Slo&#x017E;ka nejde vyrobit",
        "{CANNOT_WRITE}"=>"Nejde to zapsat",

        "{LOADED}"=>"Nahr&#x00E1;no:",
        "{NOSCRIPT}"=>"Zakaz skriptu neumozni nacist stranku spravne. Vas problem.",
        "{CLICK_CLOSE}"=>"kliknut&#x00ED;m zav&#x0159;&#x00ED;t",

        "{IMAGE_THUMB}"=>"Aktualizace n&#x00E1;hledu",
        "{IMAGE_UPLOAD}"=>"Nahr&#x00E1;n&#x00ED;",
        "{IMAGE_COPY}"=>"Kop&#x00ED;rov&#x00E1;n&#x00ED;",
        "{IMAGE_MOVE}"=>"P&#0159;esun",
        "{IMAGE_RENAME}"=>"P&#0159;ejmenov&#x00E1;n&#x00ED;",
        "{IMAGE_DELETE}"=>"Maz&#x00E1;n&#x00ED;",
        "{IMAGE_PROPS}"=>"Vlastnosti",
        "{IMAGE_DIR_PROPS}"=>"Vlastnosti slo&#x017E;ky",
        "{IMAGE_DIR_NEW}"=>"Nov&#x00E1; slo&#x;ka",

        /*        "{EDIT_FILE_TEXT}"=>"Upravuj",
                "{SAVE_TEXT}"=>"Ulo&#x017E;en&#x00ED;",
                "{CONTINUE}"=>"Pokra&#x010D;ovat",
                "{FILENAME_SET}"=>"Vyber soubor",
                "{DIRECTORY_TREE_SET}"=>"Vyber slo&#x017E;ku",*/

        "{FILES-DIRS}"=>"Soubory a slo&#x017E;ky",
        "{OF}"=>"z",
        "{FILE_OPEN_ANOTHER_USER}"=>"Soubor otev&#x0159;el ji&#x017E; n&#x011B;kdo jin&#x00FD;",

        "{MODULE_PAGE}"=>"Obr&#x00E1;zky",

        "short.add_record"=>"Dodat zpr&#x00E1;vu",
        "short.update_texts"=>"Upravit texty",
        "short.remove_record"=>"Smazat zpr&#x00E1;vu",

        "short.id"=>"ID",
        "short.title"=>"Titulek",
        "short.message"=>"Zpr&#x00E1;va",
        "short.date"=>"Datum",
        "short.actions"=>"Operace",
        "short.updated"=>"Upraveno",
        "short.removed"=>"Smaz&#x00E1;no",

        "short.create_new_file"=>"Vytvo&#x0159;en nov&#x00FD; soubor",
        "short.cannot_read"=>"Nebyl nalezen soubor se zpr&#x00E1;vami.",
        "short.cannot_write"=>"Nem&#x016F;&#x017E;u zapsat data",

        "short.add_message"=>"Dod&#x00E1;n&#x00ED; z&#x00E1;znamu",
        "short.update_message"=>"Aktualizace z&#x00E1;znam&#x016F;",
        "short.remove_message"=>"Odstran&#x011B;n&#x00ED; z&#x00E1;znam&#x016F;",

        "short.page"=>"Kr&#x00E1;tk&#x00E9; zpr&#x00E1;vy",
    ],
];
