<?php

############################################################
#       ADMIN/LANGS.PHP                                    #
#       texts for admin                                    #
#       from Kalanys@2010                                  #
############################################################
#       if you translate to new language,                  #
#       please use UTF-8 charset entities                  #
#       (for compatibility)                                #
############################################################

$lang = [
    'eng' => [
        "system.administration"=>"Administration",
        "system.to_menu"=>"To menu",
        "system.to_up"=>"Upside",
        "system.to_down"=>"Downside",
        "system.use_lang"=>"Language",

        "pager.results"=>"Showing results %d - %d of total %d",

        "{ACTION}"=>"Operation",
        "{FILE}"=>"File",
        "{SOURCE}"=>"From",
        "{DESTINATION}"=>"To",
        "{RESULT}"=>"Result",
        "{TOTAL_TEXT}"=>"Disc total",
        "{USED_TEXT}"=>"Used",
        "{FREE_TEXT}"=>"Left",
        "{DIRECTORY}"=>"Directory",
        "{DIRECTORIES}"=>"Directories",
        "{FILENAME}"=>"File",
        "{FILENAMES}"=>"Files",
        "{CURRENT_PATH}"=>"Current directory",
        "{CHANGE_DIRECTORY}"=>"Change directory",
        "{SET_SHAPES}"=>"&gt;&gt;",
        "{SUCCESS}"=>"Done",
        "{ERROR}"=>"Error",
        "{WARNING}"=>"Warning",
        "warn.must_fill"=>"Must be filled",
        "warn.late"=>"Too late!",

        "{DIRECTORY_SET}"=>"Set directory",
        "{DIRECTORY_TREE_SET}"=>"Set directory from tree",
        "{FILENAME_SET}"=>"Set file",
        "{FILENAME_SELECT}"=>"Select files",

        "dashboard.page"=>"So what?",
        "dashboard.dir_select"=>"Select directories",
        "dashboard.button_reset"=>"Cancel",
        "dashboard.button_set"=>"Set",

        "menu.chsett" => "Change settings",
        "menu.logout" => "Logout",

        "login.text" => "Login to administration",
        "login.name" => "Name",
        "login.pass" => "Password",
        "login.button" => "Log me!",
        "login.no_capt" => "You couldn't log in without captcha.",
        "login.page" => "Login page",
        "logout.text" => "You are logged out.",
        "logout.title" => "Log out done.",
        "logout.link" => "To login page",
        "logout.page" => "Log out",
    ],
    'fra' => [
        "system.administration"=>"L'administration",
        "system.to_menu"=>"Au le menu",
        "system.to_up"=>"Au le top",
        "system.to_down"=>"Au le bas",
        "system.use_lang"=>"La langue",

        "pager.results"=>"Present&#x00E9; r&#x00E9;sultats %d - %d de %d",

        "{ACTION}"=>"Op&#x00E9;ration",
        "{FILE}"=>"Fichier",
        "{SOURCE}"=>"Source",
        "{DESTINATION}"=>"O&#x00F9;",
        "{RESULT}"=>"R&#x00E9;sultat",
        "{TOTAL_TEXT}"=>"Lieu total",
        "{USED_TEXT}"=>"Utilisez",
        "{FREE_TEXT}"=>"Autres",
        "{DIRECTORY}"=>"Composant",
        "{DIRECTORIES}"=>"Composants",
        "{FILENAME}"=>"Fichier",
        "{FILENAMES}"=>"Fichiers",
        "{CURRENT_PATH}"=>"Fichier actuel",
        "{CHANGE_DIRECTORY}"=>"Changenment compasante",
        "{SET_SHAPES}"=>"&gt;&gt;",
        "{SUCCESS}"=>"Commis",
        "{ERROR}"=>"Erreur",
        "{WARNING}"=>"Attender",
        "warn.must_fill"=>"Must be filled",
        "warn.late"=>"Too late!",

        "{DIRECTORY_SET}"=>"Choisir composant",
        "{DIRECTORY_TREE_SET}"=>"Choisir composant du l'arbre",
        "{FILENAME_SET}"=>"Choisir fichier",
        "{FILENAME_SELECT}"=>"S&#x00E9;lectionnez fichiers",

        "dashboard.page"=>"Alors quoi?",
        "dashboard.dir_select"=>"S&#x00E9;lectionnez composant",
        "dashboard.button_reset"=>"Annuler",
        "dashboard.button_set"=>"Assurez-le",

        "menu.chsett" => "Modifier les param&#x00E8;tres",
        "menu.logout" => "Se d&#x00E9;sabonner",

        "login.text" => "Abonner au administration",
        "login.name" => "Nom",
        "login.pass" => "Pass",
        "login.button" => "Abonne moi!",
        "login.no_capt" => "Sauf captcha vous n'&#x00E9;tes pas abonner.",
        "login.page" => "Abonner",
        "logout.text" => "Vous &#x00E9;tes d&#x00E9;sabonner.",
        "logout.title" => "D&#x00E9;sabonner finit.",
        "logout.link" => "Au abonner.",
        "logout.page" => "D&#x00E9;sabonner",
    ],
    'cze' => [
        "system.administration"=>"Spr&#x00E1;va",
        "system.to_menu"=>"Na nab&#x00ED;dku",
        "system.to_up"=>"Nahoru",
        "system.to_down"=>"Dol&#x016F;",
        "system.use_lang"=>"Jazyk",

        "pager.results"=>"V&#x00FD;sledky %d - %d z celkem %d",

        "{ACTION}"=>"Operace",
        "{FILE}"=>"Soubor",
        "{SOURCE}"=>"Odkud",
        "{DESTINATION}"=>"Kam",
        "{RESULT}"=>"V&#x00FD;sledek",
        "{TOTAL_TEXT}"=>"M&#x00ED;sto celkem",
        "{USED_TEXT}"=>"Vyu&#x017E;ito",
        "{FREE_TEXT}"=>"Zb&#x00FD;v&#x00E1;",
        "{DIRECTORY}"=>"Slo&#x017E;ka",
        "{DIRECTORIES}"=>"Slo&#x017E;ky",
        "{FILENAME}"=>"Soubor",
        "{FILENAMES}"=>"Soubory",
        "{CURRENT_PATH}"=>"Aktu&#x00E1;ln&#x00ED; slo&#x017E;ka",
        "{CHANGE_DIRECTORY}"=>"Zm&#x011B;&#x0148; slo&#x017E;ku",
        "{SET_SHAPES}"=>"&gt;&gt;",
        "{SUCCESS}"=>"Provedeno",
        "{ERROR}"=>"Chyba",
        "{WARNING}"=>"V&#x00FD;straha",
        "warn.must_fill"=>"Must be filled",
        "warn.late"=>"Too late!",

        "{DIRECTORY_SET}"=>"Vyber slo&#x017E;ku",
        "{DIRECTORY_TREE_SET}"=>"Vyber slo&#x017E;ku ze stromu",
        "{FILENAME_SET}"=>"Vyber soubor",
        "{FILENAME_SELECT}"=>"Vyber soubory",

        "{ANOTHER_CHANGING_NOW}"=>"N&#x011B;kdo u&#x017E; to tu m&#x011B;n&#x00ED;",
        "{CANNOT_COPY_PASSWD}"=>"Nelze si ud&#x011B;lat z&#x00E1;lohu &#x00FA;&#x010D;t&#x016F;",
        "{CANNOT_LOCK_PASSWD}"=>"Nelze uzamknout &#x00FA;&#x010D;ty",
        "{CANNOT_WRITE_TO_PASSWD}"=>"Nelze zapsat do &#x00FA;&#x010D;t&#x016F;",
        "{CANNOT_COPY_SHADOW}"=>"Nelze si ud&#x011B;lat z&#x00E1;lohu hesel",
        "{CANNOT_LOCK_SHADOW}"=>"Nelze uzamknout hesla",
        "{CANNOT_WRITE_TO_SHADOW}"=>"Nelze zapsat do hesel",
        "{CANNOT_COPY_GROUPS}"=>"Nelze si ud&#x011B;lat z&#x00E1;lohu skupin",
        "{CANNOT_LOCK_GROUPS}"=>"Nelze uzamknout skupiny",
        "{CANNOT_WRITE_TO_GROUPS}"=>"Nelze zapsat do skupin",
        "{CANNOT_COPY_PASSWD_OR_SHADOW}"=>"Nelze si ud&#x011B;lat z&#x00E1;lohu &#x00FA;&#x010D;t&#x016F; &#x010D;i hesel",
        "{CANNOT_WRITE_TO_PASSWD_OR_SHADOW}"=>"Nelze zapsat do &#x00FA;&#x010D;t&#x016F; &#x010D;i hesel",
        "{TOO_LOW_CLASS_TO_REMOVE}"=>"P&#x0159;&#x00ED;li&#x0161; mal&#x00E1; pr&#x00E1;va na odebr&#x00E1;n&#x00ED;.",
        "{ONLY_CREATOR_COULD_REMOVE}"=>"Jen tv&#x016F;rce m&#x016F;&#x017E;e odebrat skupinu.",
        "{GROUP_ALREADY_EXISTS}"=>"Skupina ji&#x017E; existuje",
        "{ERROR_WITH_GROUPS_REPAIR_IT}"=>"Chyba ve skupin&#x00E1;ch, pot&#x0159;eba ru&#x010D;n&#x00ED; opravy.",
        "{TRY_TO_HACK}"=>"To se m&#x011B; jako sna&#x017E;&#x00ED;&#x0161; hacknout?",

        "dashboard.page"=>"Tak co?",
        "dashboard.dir_select"=>"Vyber slo&#x017E;ky",
        "dashboard.button_reset"=>"Zru&#x0161;it",
        "dashboard.button_set"=>"Prove&#x010F;",

        "menu.chsett" => "Zm&#x011B;na nastaven&#x00ED;",
        "menu.logout" => "Odhl&#x00E1;&#x0161;en&#x00ED;",

        "login.text" => "P&#x0159;ihl&#x00E1;&#x0161;en&#x00ED; ke spr&#x00E1;v&#x011B;",
        "login.name" => "Jm&#x00E9;no",
        "login.pass" => "Heslo",
        "login.button" => "P&#x0159;ihla&#x0161;!",
        "login.no_capt" => "Bez captchi se nep&#x0159;ihl&#x00E1;s&#x00ED;te.",
        "login.page" => "P&#x0159;ihl&#x00E1;&#x0161;en&#x00ED;",
        "logout.text" => "Byl jste odhl&#x00E1;&#x0161;en z administrace.",
        "logout.title" => "Odhl&#x00E1;&#x0161;en&#x00ED; prob&#x011B;hlo.",
        "logout.link" => "Na p&#x0159;ihl&#x00E1;&#x0161;en&#x00ED;",
        "logout.page" => "Odhl&#x00E1;&#x0161;en&#x00ED;",
    ],
];
